### ISSUE TITLE
Plus icon doens't work on web platform

### ISSUE THREAD

**Issue by MedjahdiKaram** [marcocesarato/react-native-input-spinner#19] opened 2021-01-05 12:41 UTC
the component works fine on web but it doesn't display + button

**Comment by marcocesarato** [comment] 2021-01-05 13:59
The problem is the width of the item that on web have some issue.
For fix it at the moment you just have to you enlarge the item (you can use the `width` prop or using `style`) you will see the plus button.

This issue will be fixed soon.

**Closed** 2021-01-07 18:51 UTC
